export const SET_USER_REQUEST: "SET_USER_REQUEST" = "SET_USER_REQUEST";
export const SET_USER_SUCCESS: "SET_USER_SUCCESS" = "SET_USER_SUCCESS";
export const SET_USER_FAILED: "SET_USER_FAILED" = "SET_USER_FAILED";

export const SET_REGISTER_SUCCESS: "SET_REGISTER_SUCCESS" = "SET_REGISTER_SUCCESS";
export const SET_REGISTER_FAILED: "SET_REGISTER_FAILED" = "SET_REGISTER_FAILED";

export const SET_LOGOUT_REQUEST: "SET_LOGOUT_REQUEST" = "SET_LOGOUT_REQUEST";
export const SET_LOGOUT_SUCCESS: "SET_LOGOUT_SUCCESS" = "SET_LOGOUT_SUCCESS";
export const SET_LOGOUT_FAILED: "SET_LOGOUT_FAILED" = "SET_LOGOUT_FAILED";