export const UPDATE_CONSTRUCTOR_INGREDIENTS: "UPDATE_CONSTRUCTOR_INGREDIENTS" = "UPDATE_CONSTRUCTOR_INGREDIENTS";
export const ADD_CONSTRUCTOR_INGREDIENT: "ADD_CONSTRUCTOR_INGREDIENT" = "ADD_CONSTRUCTOR_INGREDIENT";
export const DELETE_CONSTRUCTOR_INGREDIENT: "DELETE_CONSTRUCTOR_INGREDIENT" = "DELETE_CONSTRUCTOR_INGREDIENT";
export const SET_CONSTRUCTOR_BUN: "SET_CONSTRUCTOR_BUN" = "SET_CONSTRUCTOR_BUN";
export const REMOVE_CONSTRUCTOR: "REMOVE_CONSTRUCTOR" = "REMOVE_CONSTRUCTOR"