export const UPDATE_ORDER_DATE: "UPDATE_ORDER_DATE" = "UPDATE_ORDER_DATE";
export const UPDATE_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS" = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAILED: "UPDATE_ORDER_FAILED" = "UPDATE_ORDER_FAILED";